// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foo.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "foo.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace prototest {

namespace {

const ::google::protobuf::Descriptor* Foo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Foo_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_foo_2eproto() {
  protobuf_AddDesc_foo_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "foo.proto");
  GOOGLE_CHECK(file != NULL);
  Foo_descriptor_ = file->message_type(0);
  static const int Foo_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Foo, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Foo, bar_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Foo, baz_),
  };
  Foo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Foo_descriptor_,
      Foo::default_instance_,
      Foo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Foo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Foo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Foo));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_foo_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Foo_descriptor_, &Foo::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_foo_2eproto() {
  delete Foo::default_instance_;
  delete Foo_reflection_;
}

void protobuf_AddDesc_foo_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\tfoo.proto\022\tprototest\"+\n\003Foo\022\n\n\002id\030\001 \002("
    "\005\022\013\n\003bar\030\002 \002(\t\022\013\n\003baz\030\003 \001(\t", 67);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "foo.proto", &protobuf_RegisterTypes);
  Foo::default_instance_ = new Foo();
  Foo::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_foo_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_foo_2eproto {
  StaticDescriptorInitializer_foo_2eproto() {
    protobuf_AddDesc_foo_2eproto();
  }
} static_descriptor_initializer_foo_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Foo::kIdFieldNumber;
const int Foo::kBarFieldNumber;
const int Foo::kBazFieldNumber;
#endif  // !_MSC_VER

Foo::Foo()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:prototest.Foo)
}

void Foo::InitAsDefaultInstance() {
}

Foo::Foo(const Foo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:prototest.Foo)
}

void Foo::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  id_ = 0;
  bar_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  baz_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Foo::~Foo() {
  // @@protoc_insertion_point(destructor:prototest.Foo)
  SharedDtor();
}

void Foo::SharedDtor() {
  if (bar_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete bar_;
  }
  if (baz_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete baz_;
  }
  if (this != default_instance_) {
  }
}

void Foo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Foo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Foo_descriptor_;
}

const Foo& Foo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_foo_2eproto();
  return *default_instance_;
}

Foo* Foo::default_instance_ = NULL;

Foo* Foo::New() const {
  return new Foo;
}

void Foo::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    id_ = 0;
    if (has_bar()) {
      if (bar_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        bar_->clear();
      }
    }
    if (has_baz()) {
      if (baz_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        baz_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Foo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:prototest.Foo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_bar;
        break;
      }

      // required string bar = 2;
      case 2: {
        if (tag == 18) {
         parse_bar:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_bar()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->bar().data(), this->bar().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "bar");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_baz;
        break;
      }

      // optional string baz = 3;
      case 3: {
        if (tag == 26) {
         parse_baz:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_baz()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->baz().data(), this->baz().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "baz");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:prototest.Foo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:prototest.Foo)
  return false;
#undef DO_
}

void Foo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:prototest.Foo)
  // required int32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // required string bar = 2;
  if (has_bar()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->bar().data(), this->bar().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bar");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->bar(), output);
  }

  // optional string baz = 3;
  if (has_baz()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->baz().data(), this->baz().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "baz");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->baz(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:prototest.Foo)
}

::google::protobuf::uint8* Foo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:prototest.Foo)
  // required int32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // required string bar = 2;
  if (has_bar()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->bar().data(), this->bar().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bar");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->bar(), target);
  }

  // optional string baz = 3;
  if (has_baz()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->baz().data(), this->baz().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "baz");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->baz(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:prototest.Foo)
  return target;
}

int Foo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // required string bar = 2;
    if (has_bar()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->bar());
    }

    // optional string baz = 3;
    if (has_baz()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->baz());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Foo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Foo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Foo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Foo::MergeFrom(const Foo& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_bar()) {
      set_bar(from.bar());
    }
    if (from.has_baz()) {
      set_baz(from.baz());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Foo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Foo::CopyFrom(const Foo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Foo::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void Foo::Swap(Foo* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(bar_, other->bar_);
    std::swap(baz_, other->baz_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Foo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Foo_descriptor_;
  metadata.reflection = Foo_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace prototest

// @@protoc_insertion_point(global_scope)
